using static Vortice.Vulkan.Vulkan;

namespace Neko.AbstractionLayer;

[Flags]
public enum MemoryProperty {
  None = 0,
  DeviceLocal = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,
  HostVisible = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT,
  HostCoherent = VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
  HostCached = VK_MEMORY_PROPERTY_HOST_CACHED_BIT,
  LazilyAllocated = VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT,
  Protected = VK_MEMORY_PROPERTY_PROTECTED_BIT,
  DeviceCoherentAMD = VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD,
  DeviceUncachedAMD = VK_MEMORY_PROPERTY_DEVICE_UNCACHED_BIT_AMD,
  RDMACapableNV = VK_MEMORY_PROPERTY_RDMA_CAPABLE_BIT_NV,
}
